// SPDX-License-Identifier: GPL-3.0-only
//! The two language tables. Every word a person reads in this program is here
//! and nowhere else; the wire spellings a row also shows — raw event types,
//! module names, ids, schema strings, sha256 — are never translated.
//!
//! The chosen table is read once at startup, into the `Strings` global for the
//! labels the window draws itself and directly for the lines the console fills.

/// `zh` or `en`, as the settings file and `--lang` spell it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Language {
    Zh,
    En,
}

impl Language {
    pub const fn wire(self) -> &'static str {
        match self {
            Self::Zh => "zh",
            Self::En => "en",
        }
    }

    pub fn from_wire(text: &str) -> Option<Self> {
        match text {
            "zh" => Some(Self::Zh),
            "en" => Some(Self::En),
            _ => None,
        }
    }

    pub const fn labels(self) -> &'static Labels {
        match self {
            Self::Zh => &ZH,
            Self::En => &EN,
        }
    }
}

/// One language. Arrays are indexed by the contract's own ordering; the pair
/// tables are keyed by the wire string or by a stable field key.
pub struct Labels {
    /// Which of the two tables this is, for the dictionary lookups in `acui-rows`.
    pub tongue: Language,
    pub window_title: &'static str,
    pub usage: &'static str,
    pub data_source: &'static str,
    pub data_source_online: &'static str,
    pub ledger_dir: &'static str,
    pub storage_format: &'static str,
    /// The two media the ledger picks between, in `backend()` spelling order.
    pub storage_segments: &'static str,
    pub storage_sqlite: &'static str,
    /// Online: the Runtime answers pages without stating its medium.
    pub storage_runtime: &'static str,
    /// Lowest and highest position the loaded windows cover.
    pub read_range: &'static str,
    /// Hidden performance-monitor events; appended to the loaded-rows line.
    pub performance_hidden: &'static str,
    pub show_performance: &'static str,
    pub source_incomplete: &'static str,
    pub read_up_to_unknown: &'static str,
    pub loaded_rows_top: &'static str,
    pub loaded_badge: &'static str,
    pub show_up_to: &'static str,
    pub all: &'static str,
    pub text_size: &'static str,
    pub text_sizes: [&'static str; 3],
    pub language: &'static str,
    pub languages: [&'static str; 2],
    pub restart_note: &'static str,
    pub severity_min: [&'static str; 4],
    pub severity_max: [&'static str; 4],
    pub all_modules: &'static str,
    /// The port box: its first item, one item per port (port, latest member
    /// id), and the one item it shows when it is disabled and why.
    pub all_instances: &'static str,
    pub port_option: &'static str,
    pub no_binding_records: &'static str,
    pub port_online_unsupported: &'static str,
    /// The port column of a row that links no instance.
    pub host: &'static str,
    pub id_placeholder: &'static str,
    pub continue_reading: &'static str,
    pub card_title: &'static str,
    pub card_note: &'static str,
    pub detail_title: &'static str,
    pub artifacts_title: &'static str,
    pub overlays_title: &'static str,
    pub raw_data_title: &'static str,
    pub no_event_selected: &'static str,
    pub not_selected: &'static str,
    /// seq, time, level, module, event, link, port.
    pub columns: [&'static str; 7],
    /// The #109 view names, in `LedgerView::ALL` order.
    pub tabs: [&'static str; 6],
    /// debug, info, warning, error, fatal.
    pub levels: [&'static str; 5],
    /// public, internal, sensitive, secret.
    pub sensitivities: [&'static str; 4],
    /// `EventSource`, in the contract's declaration order.
    pub sources: [(&'static str, &'static str); 8],
    /// Field key to label, for the instance card and the detail pane.
    pub fields: [(&'static str, &'static str); 50],
    /// `ExecutionBackendProvenance`, by wire value.
    pub provenances: [(&'static str, &'static str); 2],
    pub artifact_kinds: [(&'static str, &'static str); 6],
    pub media_types: [(&'static str, &'static str); 4],
    pub checksum: &'static str,
    pub none: &'static str,
    /// A ledger count over an incomplete read, a medium without a repair log,
    /// and a count the online Runtime does not state.
    pub count_verified_prefix: &'static str,
    pub count_no_repair_log: &'static str,
    pub count_not_stated: &'static str,
    /// recovered, unresolved, unknown.
    pub recovery_states: [&'static str; 3],
    pub recovery_gaps: [(&'static str, &'static str); 4],
    pub run_prefix: &'static str,
    pub failed_recovered: &'static str,
    pub failed_only: &'static str,
    pub gap_prefix: &'static str,
    pub join: &'static str,
    pub recovered_badge: &'static str,
    pub integrity_ok: &'static str,
    pub integrity_bad: &'static str,
    pub writer_absent: &'static str,
    pub writer_locked: &'static str,
    pub writer_running: &'static str,
    pub writer_stopped: &'static str,
    pub writer_runtime: &'static str,
    /// The instance card's read-face line: online, or offline and why.
    pub source_online: &'static str,
    pub source_offline_requested: &'static str,
    pub source_offline_absent: &'static str,
    pub source_offline_failed: &'static str,
    /// The offline face the ledger refused to open: ledger code, operation,
    /// detail; the hint only follows `ledger_io` with io kind `not_found`.
    pub source_unopened: &'static str,
    pub source_unopened_hint: &'static str,
    /// The ledger's io kind; appended to the unopened line.
    pub io_kind_text: &'static str,
    /// Unopened: the top bar and the two boxes, then the list and the frame pane.
    pub ledger_unopened: &'static str,
    pub list_unopened: &'static str,
    pub age_days: &'static str,
    pub age_hours: &'static str,
    pub age_minutes: &'static str,
    pub age_seconds: &'static str,
    pub frame_size: &'static str,
    pub frame_size_missing: &'static str,
    pub frame_reading: &'static str,
    pub frame_verified: &'static str,
    pub frame_no_artifact: &'static str,
    pub frame_unavailable: &'static str,
    pub frame_evicted: &'static str,
    pub frame_decode_failed: &'static str,
    pub frame_too_large: &'static str,
    pub filter_id_error: &'static str,
    pub filter_instance_conflict: &'static str,
    pub filter_rejected: &'static str,
    pub read_failed: &'static str,
    /// The launcher block in the top bar: status, two buttons, one line.
    pub launcher_title: &'static str,
    pub start: &'static str,
    pub request_shutdown: &'static str,
    /// pid, owner epoch.
    pub runtime_running: &'static str,
    /// client error code, client operation.
    pub runtime_not_running: &'static str,
    pub already_running: &'static str,
    /// The OS error of a worker thread that could not be started.
    pub thread_failed: &'static str,
    /// actingd's pid, the OS error.
    pub start_unwatched: &'static str,
    pub start_busy: &'static str,
    /// settings key.
    pub key_not_configured: &'static str,
    /// settings key, value.
    pub key_not_absolute: &'static str,
    /// directory, error.
    pub log_dir_failed: &'static str,
    /// executable, error.
    pub spawn_failed: &'static str,
    /// error.
    pub child_status_failed: &'static str,
    /// pid, attempt, attempts, log path.
    pub start_waiting: &'static str,
    /// exit code, the log's last `FATAL actingd:` line or why there is none,
    /// log path.
    pub start_exited: &'static str,
    /// pid, owner epoch.
    pub start_ready: &'static str,
    pub restart_online: &'static str,
    /// attempts, client error code, client operation.
    pub start_not_ready: &'static str,
    /// The start press as a client action: its sequence.
    pub start_recorded: &'static str,
    /// runtime refusal code, client error code, client operation.
    pub start_record_refused: &'static str,
    /// client error code, client operation.
    pub start_record_failed: &'static str,
    pub log_no_fatal: &'static str,
    /// error.
    pub log_unreadable: &'static str,
    /// The unlock entry, offered after a start whose fatal line names
    /// `owner_resource_unconfirmed`: its button, the statement the second
    /// press makes, and the button that makes it.
    pub unlock_owner: &'static str,
    pub unlock_statement: &'static str,
    pub unlock_confirm: &'static str,
    pub unlock_busy: &'static str,
    /// actor.
    pub unlock_running: &'static str,
    /// owner epoch, previous resource disposition, revision.
    pub unlock_ok: &'static str,
    /// exit code, owner epoch, previous resource disposition, revision.
    pub unlock_ok_nonzero: &'static str,
    /// error code, stage, journal_appended, exit code.
    pub unlock_failed: &'static str,
    /// exit code, the `FATAL actingd:` line.
    pub unlock_fatal: &'static str,
    /// why, exit code.
    pub unlock_unparseable: &'static str,
    /// JSON pointer.
    pub unlock_field_invalid: &'static str,
    pub unlock_no_output: &'static str,
    /// seconds.
    pub unlock_timeout: &'static str,
    pub unlock_killed: &'static str,
    /// error.
    pub unlock_kill_failed: &'static str,
    /// The wait's error, after a kill that worked.
    pub unlock_unreaped: &'static str,
    /// error.
    pub unlock_output_failed: &'static str,
    pub unlock_spawn_failed: &'static str,
    /// attempt, attempts.
    pub shutdown_busy_retry: &'static str,
    /// attempts sent, attempts.
    pub shutdown_attempts: &'static str,
    /// receipt state, request id, action sequence.
    pub shutdown_accepted: &'static str,
    /// runtime refusal code, client error code, client operation.
    pub shutdown_refused: &'static str,
    /// client error code, client operation.
    pub shutdown_failed: &'static str,
    /// The instance-configuration window, and the top-bar button that opens it.
    pub instance_config: &'static str,
    pub config_intro: &'static str,
    pub add_instance: &'static str,
    /// alias, instance_id, binding, adb_path, nemu_app_index, application_id,
    /// capture_backend, touch_backend.
    pub form_fields: [&'static str; 8],
    pub binding_kinds: [&'static str; 3],
    /// instance_index, instance_name, host, port; adb_path optional, then
    /// required; nemu_app_index.
    pub form_placeholders: [&'static str; 7],
    pub optional_note: &'static str,
    pub check_and_save: &'static str,
    /// error.
    pub id_failed: &'static str,
    /// field; field, largest value, value.
    pub value_missing: &'static str,
    pub value_not_number: &'static str,
    /// config path; config path, error; config path, error; config path.
    pub config_missing: &'static str,
    pub config_unreadable: &'static str,
    pub config_not_json: &'static str,
    pub config_no_instances: &'static str,
    pub checking: &'static str,
    /// candidate path, error; error.
    pub candidate_failed: &'static str,
    pub reader_failed: &'static str,
    /// seconds; exit code, output; error.code, stage; exit code; exit code, error; exit code.
    pub check_timeout: &'static str,
    pub check_unparsed: &'static str,
    pub check_failed: &'static str,
    pub check_ok_nonzero: &'static str,
    pub check_read_failed: &'static str,
    pub check_reader_lost: &'static str,
    /// Ends a failure that stopped check-config; error.
    pub check_stopped: &'static str,
    pub check_unstoppable: &'static str,
    /// The wait's error, after a kill that worked.
    pub check_unreaped: &'static str,
    /// config path, error; candidate path, error.
    pub replace_failed: &'static str,
    pub candidate_left: &'static str,
    /// Ends every failed save.
    pub config_unchanged: &'static str,
    /// config path.
    pub saved: &'static str,
    /// Runtime status as the launcher words it.
    pub saved_running: &'static str,
    pub saved_stopped: &'static str,
    /// config path, instance count; config path, entry number counted from 1.
    pub config_listed: &'static str,
    pub config_bad_entry: &'static str,
    /// Online; error; port; bound outside the port map; not bound.
    pub ledger_online: &'static str,
    pub ledger_failed: &'static str,
    pub ledger_port: &'static str,
    pub ledger_outside_map: &'static str,
    pub ledger_none: &'static str,
    /// index; name; host, port; serial.
    pub binding_index: &'static str,
    pub binding_name: &'static str,
    pub binding_adb: &'static str,
    pub binding_serial: &'static str,
    pub binding_none: &'static str,
    pub binding_fixture: &'static str,
    /// instance_id, application_id, capture_backend, touch_backend.
    pub instance_detail: &'static str,
    /// instance_id.
    pub entry_gone: &'static str,
    pub entry_no_id: &'static str,
    pub entry_serial: &'static str,
    pub entry_fixture: &'static str,
    pub entry_no_binding: &'static str,
    /// The ledger column of a row without a string instance_id.
    pub row_no_id: &'static str,
    pub instances_none: &'static str,
    pub offline_not_provided: &'static str,
    pub facts_none: &'static str,
    pub facts_no_events: &'static str,
    /// The read face's reason.
    pub facts_not_available: &'static str,
    /// The instance lines' first line when a read failed; the lines below it
    /// say how.
    pub instances_unread: &'static str,
    pub lease_active: &'static str,
    pub lease_cooldown: &'static str,
    pub lease_idle: &'static str,
    /// Lease text, queued request count.
    pub lease_queued: &'static str,
    pub not_registered: &'static str,
    pub fact_unrecorded: &'static str,
    /// Host code, host operation; appended to a client failure.
    pub host_failure: &'static str,
    pub discover: &'static str,
    pub discover_use: &'static str,
    /// The discovery box's first item, which picks nothing.
    pub discover_pick: &'static str,
    pub discovering: &'static str,
    /// Instance count, provider version, observation sequence.
    pub discovered: &'static str,
    /// Runtime code, client code, operation; client code, operation.
    pub discover_refused: &'static str,
    pub discover_failed: &'static str,
    /// The OS error.
    pub discover_spawn_failed: &'static str,
    /// MuMu index.
    pub discovered_index: &'static str,
    pub instance_running: &'static str,
    pub instance_stopped: &'static str,
    /// Android version.
    pub android_version: &'static str,
    /// Bound alias.
    pub bound_to: &'static str,
    /// MuMu index, bound alias.
    pub discover_bound: &'static str,
    /// MuMu index, the alias of the file's entry for that instance.
    pub discover_listed: &'static str,
    /// MuMu index, instance name.
    pub discover_applied: &'static str,
}

pub const ZH: Labels = Labels {
    tongue: Language::Zh,
    window_title: "ActingCommand 监控台",
    usage: "用法：acui [--state-root <状态根>] [--source <auto|offline|online>] [--tab <events|observation|changes|errors|health|lab>] [--lang <zh|en>]\n不给 --state-root 时取 acui.toml 的 state_root；两处都没有就不开台。",
    data_source: "数据来源：本机账本（只读）",
    data_source_online: "数据来源：运行中的 Runtime（只读）",
    ledger_dir: "账本目录",
    storage_format: "存储格式",
    storage_segments: "分段文件",
    storage_sqlite: "SQLite",
    storage_runtime: "由 Runtime 判定",
    read_range: "已读序号 {}–{}",
    performance_hidden: " · 另有 {} 条性能监视例行事件已隐藏",
    show_performance: "显示性能监视",
    source_incomplete: "源不完整",
    read_up_to_unknown: "读取范围未给",
    loaded_rows_top: "已载入 {} 条",
    loaded_badge: "已载入 {}",
    show_up_to: "只看到",
    all: "全部",
    text_size: "字号",
    text_sizes: ["标准", "大", "特大"],
    language: "语言",
    languages: ["中文", "English"],
    restart_note: "重启后生效",
    severity_min: ["严重度不限", "≥ 警告", "≥ 错误", "≥ 致命"],
    severity_max: ["上限不限", "≤ 信息", "≤ 警告", "≤ 错误"],
    all_modules: "全部模块",
    all_instances: "全部实例",
    port_option: "端口 {} ／ {}",
    no_binding_records: "无绑定记录",
    port_online_unsupported: "在线态不支持",
    host: "宿主",
    id_placeholder: "完整的 correlation_ / request_ / run_ / task_ / instance_ 编号",
    continue_reading: "读更早",
    card_title: "实例卡",
    card_note: "账本事实取自读面；条数与级别计数只算已载入的行，不含隐藏的性能监视事件",
    detail_title: "详情",
    artifacts_title: "附带材料",
    overlays_title: "识别框与点击点",
    raw_data_title: "原始数据",
    no_event_selected: "未选中事件",
    not_selected: "未选中",
    columns: [
        "序号",
        "时间（本地）",
        "级别",
        "来源模块",
        "事件",
        "关联：请求／任务／运行",
        "端口",
    ],
    tabs: ["事件流", "观察与操作", "变更", "错误", "运行状况", "Lab"],
    levels: ["调试", "信息", "警告", "错误", "致命"],
    sensitivities: ["公开", "内部", "敏感", "机密"],
    sources: [
        ("runtime", "运行时"),
        ("scheduler", "调度器"),
        ("device", "设备"),
        ("cli", "命令行"),
        ("ui", "界面"),
        ("lab", "实验台"),
        ("system", "系统"),
        ("adapter", "适配器"),
    ],
    fields: [
        ("source", "读面"),
        ("latest_sequence", "账本最新序号"),
        ("event_count", "账本事件总数"),
        ("loaded_rows", "已载入条数"),
        ("first_event", "最早一条时间"),
        ("latest_event", "最新一条时间"),
        ("age", "距今"),
        ("integrity", "账本是否完整"),
        ("repair_count", "修复记录数"),
        ("writer", "写入进程：编号／PID／是否仍在运行"),
        ("modules", "出现过的模块"),
        ("sequence", "序号"),
        ("event_id", "事件编号"),
        ("occurred_at", "发生时间"),
        ("event_type", "事件"),
        ("severity", "级别"),
        ("sensitivity", "敏感度"),
        ("origin", "来源：系统／模块／操作者"),
        ("views", "所属视图"),
        ("payload_schema", "载荷格式"),
        ("request_id", "请求编号"),
        ("correlation_id", "关联编号"),
        ("causation_id", "因果编号"),
        ("action_id", "动作编号"),
        ("run_id", "运行编号"),
        ("task_id", "任务编号"),
        ("instance_id", "实例编号"),
        ("recognition_id", "识别编号"),
        ("frame_id", "帧编号"),
        ("lease_id", "租约编号"),
        ("instance_alias", "实例别名"),
        ("adb_port", "端口"),
        ("provenance", "来源"),
        ("bound_ids", "绑定编号数"),
        ("latest_binding", "最新绑定序号"),
        ("port_bindings", "实例绑定"),
        ("runtime_instances", "实例（开台时读）"),
        ("instances_status_at", "状态读于序号"),
        ("instances_facts_at", "事实读于序号"),
        ("lease", "租约"),
        ("task_game", "游戏"),
        ("task_server", "区服"),
        ("task_page", "最近识别页面"),
        ("runtime_refusal", "Runtime 拒绝码"),
        ("client_error", "客户端错误"),
        ("host_failure", "宿主失败"),
        ("instance_facts", "实例事实·钉点序号"),
        ("facts_error", "事实读取错误"),
        ("facts_detail", "详情"),
        ("io_kind", "IO 类别"),
    ],
    provenances: [
        ("physical_device", "实机"),
        ("fixture_simulation", "夹具"),
    ],
    artifact_kinds: [
        ("capture.frame", "截图帧"),
        ("diagnostic.json", "诊断数据"),
        ("evidence.archive", "证据包"),
        ("evidence.manifest", "证据清单"),
        ("report.text", "文字报告"),
        ("report.strategy", "策略报告"),
    ],
    media_types: [
        ("image/png", "PNG"),
        ("application/json", "JSON"),
        ("application/zip", "ZIP"),
        ("text/plain", "纯文本"),
    ],
    checksum: "校验值",
    none: "—",
    count_verified_prefix: "{}（读取不完整，只计已校验的前缀）",
    count_no_repair_log: "—（此存储格式没有修复日志）",
    count_not_stated: "—（Runtime 不提供此项）",
    recovery_states: ["已恢复", "未解决", "未知"],
    recovery_gaps: [
        ("missing_relation", "缺关系"),
        ("conflicting_outcome", "结果冲突"),
        ("source_incomplete", "源不完整"),
        ("context_limit", "上下文受限"),
    ],
    run_prefix: "一次运行：",
    failed_recovered: "第 {} 条失败，第 {} 条已恢复",
    failed_only: "第 {} 条失败，未见恢复",
    gap_prefix: "；缺口 ",
    join: "；",
    recovered_badge: "已恢复",
    integrity_ok: "完整",
    integrity_bad: "不完整：读全={} · 损坏尾部={}",
    writer_absent: "无写入进程记录",
    writer_locked: "记录被占用（{} 字节）",
    writer_running: "{} · PID {} · 仍在运行 · 起 {}",
    writer_stopped: "{} · PID {} · 已停止 · 起 {}",
    writer_runtime: "运行中的 Runtime · PID {} · {} · 起 {}",
    source_online: "在线 · 经 runtime-client 直连运行中的 Runtime",
    source_offline_requested: "离线 · 按 --source offline",
    source_offline_absent: "离线 · 自动：状态根里没有 runtime-info.json",
    source_offline_failed: "离线 · 自动：连接 Runtime 失败 {}（{}）",
    source_unopened: "账本未能打开：{}（{}）· {}",
    source_unopened_hint: "状态根里还没有账本，多半是 Runtime 从未在这里启动过；可用启动器的「启动」",
    io_kind_text: " · IO 类别 {}",
    ledger_unopened: "账本未打开",
    list_unopened: "账本未打开：没有读取任何事件，原因见实例卡",
    age_days: "{} 天前",
    age_hours: "{} 小时前",
    age_minutes: "{} 分钟前",
    age_seconds: "{} 秒前",
    frame_size: "画面 {}×{}",
    frame_size_missing: "未记录画面尺寸",
    frame_reading: "正在读取并全量校验 {} 字节…",
    frame_verified: "已校验帧 {}×{} · 整份 sha256 校验通过",
    frame_no_artifact: "本条没有截图帧，只画几何叠加",
    frame_unavailable: "素材未提供：{}",
    frame_evicted: "材料已淘汰（{}）：意图 #{}{} · 观察至 #{}",
    frame_decode_failed: "PNG 解码失败：{}",
    frame_too_large: "素材 {} 字节超出监控台上限 {} 字节",
    filter_id_error: "编号需填完整的 correlation_ / request_ / run_ / task_ / instance_ 标识",
    filter_instance_conflict: "端口与实例编号只能选一",
    filter_rejected: "过滤条件无效：{}",
    read_failed: "读取失败：{}",
    launcher_title: "启动器",
    start: "启动",
    request_shutdown: "请求关闭",
    runtime_running: "Runtime 运行中 · PID {} · owner epoch {}",
    runtime_not_running: "Runtime 未运行 · {}（{}）",
    already_running: "已在运行，未拉起",
    thread_failed: "无法启动后台线程：{}",
    start_unwatched: "已拉起 actingd（PID {}），但等待就绪的线程启动失败：{}；要知道它是否就绪，再按一次「启动」探测",
    start_busy: "上一次启动仍在等待就绪",
    key_not_configured: "acui.toml 未配置 {}",
    key_not_absolute: "acui.toml 的 {} 不是绝对路径：{}",
    log_dir_failed: "无法建立日志目录 {}：{}",
    spawn_failed: "拉起 {} 失败：{}",
    child_status_failed: "读取子进程状态失败：{}",
    start_waiting: "已拉起 PID {} · 等待就绪 {}/{} · 日志 {}",
    start_exited: "actingd 已退出，退出码 {} · {} · 日志 {}",
    start_ready: "Runtime 已就绪 · PID {} · owner epoch {}",
    restart_online: "本台按离线读；要在线读请带 --source online 重启",
    start_not_ready: "{} 次尝试后仍未就绪 · 最后错误 {}（{}）",
    start_recorded: "动作已记账 #{}",
    start_record_refused: "动作记账被拒：{} · 客户端 {}（{}）",
    start_record_failed: "动作记账失败：{}（{}）",
    log_no_fatal: "日志里没有 FATAL actingd: 行",
    log_unreadable: "读取日志失败：{}",
    unlock_owner: "解锁 owner…",
    unlock_statement: "确认：上一个 Runtime 的设备资源已经释放",
    unlock_confirm: "确认并解锁",
    unlock_busy: "解锁仍在进行",
    unlock_running: "正在运行 actingd unlock-owner --actor {} --confirm-resources-released…",
    unlock_ok: "已解锁 owner epoch {} · 解锁前处置 {} · owner.lock 修订 {} · 已自动重试启动一次（结果见上一行）",
    unlock_ok_nonzero: "unlock-owner 报 ok 却以退出码 {} 结束：不算解锁成功，未重试启动 · owner epoch {} · 解锁前处置 {} · owner.lock 修订 {}",
    unlock_failed: "解锁失败：{}（阶段 {}）· journal_appended={} · 退出码 {}",
    unlock_fatal: "unlock-owner 退出码 {} · {}",
    unlock_unparseable: "unlock-owner 输出无法解析：{} · 退出码 {}",
    unlock_field_invalid: "字段 {} 缺失或不合约定",
    unlock_no_output: "stdout 没有 JSON，stderr 没有 FATAL actingd: 行",
    unlock_timeout: "unlock-owner {} 秒内未结束，结果未知",
    unlock_killed: "已终止并回收",
    unlock_kill_failed: "终止失败：{}",
    unlock_unreaped: "已终止，但回收失败：{}",
    unlock_output_failed: "读取 unlock-owner 输出失败：{} · 退出码 {}",
    unlock_spawn_failed: "运行 unlock-owner（{}）失败：{}",
    shutdown_busy_retry: "请求关闭 · 忙碌重试 {}/{}",
    shutdown_attempts: "第 {}/{} 次",
    shutdown_accepted: "关闭请求已受理 · 回执 {} · 请求 {} · 动作已记账 #{}",
    shutdown_refused: "关闭请求被拒：{} · 客户端 {}（{}）",
    shutdown_failed: "关闭请求失败：{}（{}）",
    instance_config: "实例配置",
    config_intro: "列出 actingd_config 的 instances。点一行载入下面的表单编辑，或「新增实例」另起一项，然后「校验并保存」：先在同一目录写临时文件，交 actingd check-config 校验，通过才替换原文件；表单不管的键与值原样保留、键的次序不变，整份文件按 2 空格缩进的 JSON 重新写出。改动在 Runtime 重启后生效。",
    add_instance: "新增实例",
    form_fields: ["alias（必填）", "instance_id", "绑定方式", "adb_path", "nemu_app_index", "application_id", "capture_backend", "touch_backend"],
    binding_kinds: ["MuMu 序号 instance_index", "MuMu 名称 instance_name", "ADB 地址 host + port"],
    form_placeholders: ["instance_index（0–65535）", "instance_name", "host", "port（0–65535）", "选填：留空则用 MuMu 发现报告的 adb", "必填：adb 可执行文件的路径", "选填（0–4294967295）"],
    optional_note: "adb_path 在 ADB 地址方式下必填、MuMu 方式下选填；nemu_app_index 选填。application_id 与两个后端表单不检查，要不要填、取值是否有效都由 check-config 判定。nemu_app_index 的配对也由 check-config 查；只有要靠 MuMu 发现结果的几项——MuMuManager 版本与能力、发现结果恰好匹配一个、adb_path 等声明值与发现值不冲突、ADB 端点——到 Runtime 启动时才查。留空的框不写进文件。",
    check_and_save: "校验并保存",
    id_failed: "生成 instance_id 失败：{}",
    value_missing: "{} 不能为空",
    value_not_number: "{} 须为 0–{} 的整数：{}",
    config_missing: "{} 不存在",
    config_unreadable: "读取 {} 失败：{}",
    config_not_json: "{} 不是合法的 JSON：{}",
    config_no_instances: "{} 里没有 instances 数组",
    checking: "正在用 check-config 校验…",
    candidate_failed: "写临时文件 {} 失败：{}",
    reader_failed: "无法启动读取 check-config 输出的线程：{}",
    check_timeout: "check-config {} 秒内未结束",
    check_unparsed: "check-config 的输出无法识别（退出码 {}）：{}",
    check_failed: "check-config 未通过 · error.code {} · stage {}",
    check_ok_nonzero: "check-config 报 ok 但退出码为 {}，不保存",
    check_read_failed: "读取 check-config 的输出失败（退出码 {}）：{}",
    check_reader_lost: "读取 check-config 输出的线程异常结束，输出未取得（退出码 {}）",
    check_stopped: "；已终止 check-config",
    check_unstoppable: "；终止 check-config 失败（{}），它可能仍在运行",
    check_unreaped: "；已终止 check-config，但回收它失败（{}）",
    replace_failed: "替换 {} 失败：{}",
    candidate_left: "；临时文件 {} 未能删除：{}",
    config_unchanged: " · 原配置未改动",
    saved: "已保存进 {}（check-config 通过）· Runtime 重启后生效",
    saved_running: "现在：{} · 在主窗口先「请求关闭」，停下后再「启动」",
    saved_stopped: "现在：{} · 在主窗口点「启动」即按新配置运行",
    config_listed: "{} · 共 {} 个实例",
    config_bad_entry: "{} 的 instances 第 {} 项不是对象",
    ledger_online: "账本绑定：在线读面不给",
    ledger_failed: "账本绑定读取失败：{}",
    ledger_port: "账本已绑定 · 端口 {}",
    ledger_outside_map: "账本已绑定 · 最新一次不在端口映射里（序列号配置或无端口）",
    ledger_none: "账本里没有此实例的绑定",
    binding_index: "MuMu 序号 {}",
    binding_name: "MuMu 名称 {}",
    binding_adb: "ADB {}:{}",
    binding_serial: "ADB 序列号 {}",
    binding_none: "文件未写绑定键",
    binding_fixture: "fixture_backend（不连设备）",
    instance_detail: "{} · 应用 {} · 截图 {} · 触控 {}",
    entry_gone: "配置文件里已没有 {}（别处改过）",
    entry_no_id: "这一项没有字符串 instance_id，不能在这里编辑",
    entry_serial: "这一项设了 serial，表单表示不了，不能在这里编辑",
    entry_fixture: "这一项配置了 fixture_backend，表单表示不了这种后端，不能在这里编辑",
    entry_no_binding: "这一项文件里没写绑定键（MuMu 序号、MuMu 名称、host / port、serial 都没有），表单表示不了，不能在这里编辑",
    row_no_id: "不可编辑：没有字符串 instance_id",
    instances_none: "无登记实例",
    offline_not_provided: "离线读面不提供",
    facts_none: "无任务事实",
    facts_no_events: "账本里还没有事件",
    facts_not_available: "不可用：{}",
    instances_unread: "读取失败，原因见下",
    lease_active: "占用中",
    lease_cooldown: "接管冷却中",
    lease_idle: "空闲",
    lease_queued: "{} · 排队 {}",
    not_registered: "未登记（仅有任务事实）",
    fact_unrecorded: "未记录",
    host_failure: " · 宿主 {}（{}）",
    discover: "发现实例",
    discover_use: "采用所选",
    discover_pick: "选一个发现的实例…",
    discovering: "正在请 Runtime 发现实例…",
    discovered: "发现 {} 个实例 · MuMuManager {} · 读于序号 {}",
    discover_refused: "发现被拒：{} · 客户端 {}（{}）",
    discover_failed: "发现失败：{}（{}）",
    discover_spawn_failed: "无法启动发现线程：{}",
    discovered_index: "序号 {}",
    instance_running: "运行中",
    instance_stopped: "未运行",
    android_version: "Android {}",
    bound_to: "已绑定 {}",
    discover_bound: "序号 {} 已被运行中的 Runtime 绑定到 {}，不另起新项",
    discover_listed: "序号 {} 的实例在配置文件里已有对应项（{}），请在上面的列表里编辑它",
    discover_applied: "已按发现结果起一个新项：MuMu 序号 {}（{}）。填好别名等再「校验并保存」",
};

pub const EN: Labels = Labels {
    tongue: Language::En,
    window_title: "ActingCommand Console",
    usage: "Usage: acui [--state-root <state_root>] [--source <auto|offline|online>] [--tab <events|observation|changes|errors|health|lab>] [--lang <zh|en>]\nWithout --state-root the state_root key of acui.toml is used; with neither, the console does not open.",
    data_source: "Data Source: Local Ledger (Read-Only)",
    data_source_online: "Data Source: Running Runtime (Read-Only)",
    ledger_dir: "Ledger Directory",
    storage_format: "Storage Format",
    storage_segments: "Segments",
    storage_sqlite: "SQLite",
    storage_runtime: "Chosen by the Runtime",
    read_range: "Read Positions {}–{}",
    performance_hidden: " · {} Routine Performance-Monitor Events Hidden",
    show_performance: "Show Performance Monitor",
    source_incomplete: "Source Incomplete",
    read_up_to_unknown: "Read Range Not Given",
    loaded_rows_top: "Loaded Rows: {}",
    loaded_badge: "Loaded {}",
    show_up_to: "Show Up To",
    all: "All",
    text_size: "Text Size",
    text_sizes: ["Standard", "Large", "Extra Large"],
    language: "Language",
    languages: ["中文", "English"],
    restart_note: "Takes effect after restart",
    severity_min: ["Any Level", "≥ Warning", "≥ Error", "≥ Fatal"],
    severity_max: ["Any Upper Bound", "≤ Info", "≤ Warning", "≤ Error"],
    all_modules: "All Modules",
    all_instances: "All Instances",
    port_option: "Port {} ／ {}",
    no_binding_records: "No Binding Records",
    port_online_unsupported: "Not in Online Mode",
    host: "Host",
    id_placeholder: "Whole correlation_ / request_ / run_ / task_ / instance_ id",
    continue_reading: "Read Earlier",
    card_title: "Instance Card",
    card_note: "Ledger facts come from the read face; row and level counts cover the loaded rows only, without hidden performance-monitor events",
    detail_title: "Detail",
    artifacts_title: "Attached Materials",
    overlays_title: "Recognition Boxes and Tap Points",
    raw_data_title: "Raw Data",
    no_event_selected: "No event selected",
    not_selected: "Not Selected",
    columns: [
        "Seq",
        "Time (Local)",
        "Level",
        "Source Module",
        "Event",
        "Link: Request／Task／Run",
        "Port",
    ],
    tabs: ["Event Stream", "Observe and Act", "Changes", "Errors", "Health", "Lab"],
    levels: ["Debug", "Info", "Warning", "Error", "Fatal"],
    sensitivities: ["Public", "Internal", "Sensitive", "Secret"],
    sources: [
        ("runtime", "Runtime"),
        ("scheduler", "Scheduler"),
        ("device", "Device"),
        ("cli", "CLI"),
        ("ui", "UI"),
        ("lab", "Lab"),
        ("system", "System"),
        ("adapter", "Adapter"),
    ],
    fields: [
        ("source", "Read Face"),
        ("latest_sequence", "Latest Sequence"),
        ("event_count", "Total Events"),
        ("loaded_rows", "Loaded Rows"),
        ("first_event", "First Event"),
        ("latest_event", "Latest Event"),
        ("age", "Age"),
        ("integrity", "Ledger Integrity"),
        ("repair_count", "Repair Records"),
        ("writer", "Writer: ID／PID／Running"),
        ("modules", "Modules Seen"),
        ("sequence", "Sequence"),
        ("event_id", "Event ID"),
        ("occurred_at", "Occurred At"),
        ("event_type", "Event"),
        ("severity", "Level"),
        ("sensitivity", "Sensitivity"),
        ("origin", "Origin: Source／Module／Actor"),
        ("views", "Views"),
        ("payload_schema", "Payload Schema"),
        ("request_id", "Request ID"),
        ("correlation_id", "Correlation ID"),
        ("causation_id", "Causation ID"),
        ("action_id", "Action ID"),
        ("run_id", "Run ID"),
        ("task_id", "Task ID"),
        ("instance_id", "Instance ID"),
        ("recognition_id", "Recognition ID"),
        ("frame_id", "Frame ID"),
        ("lease_id", "Lease ID"),
        ("instance_alias", "Alias"),
        ("adb_port", "Port"),
        ("provenance", "Provenance"),
        ("bound_ids", "Bound IDs"),
        ("latest_binding", "Latest Binding"),
        ("port_bindings", "Instance Bindings"),
        ("runtime_instances", "Instances (Read at Open)"),
        ("instances_status_at", "Status at Sequence"),
        ("instances_facts_at", "Facts at Sequence"),
        ("lease", "Lease"),
        ("task_game", "Game"),
        ("task_server", "Server"),
        ("task_page", "Last Matched Page"),
        ("runtime_refusal", "Runtime Refusal"),
        ("client_error", "Client Error"),
        ("host_failure", "Host Failure"),
        ("instance_facts", "Instance Facts at Pin"),
        ("facts_error", "Fact Read Error"),
        ("facts_detail", "Detail"),
        ("io_kind", "IO Kind"),
    ],
    provenances: [
        ("physical_device", "Physical Device"),
        ("fixture_simulation", "Fixture"),
    ],
    artifact_kinds: [
        ("capture.frame", "Capture Frame"),
        ("diagnostic.json", "Diagnostic Data"),
        ("evidence.archive", "Evidence Archive"),
        ("evidence.manifest", "Evidence Manifest"),
        ("report.text", "Text Report"),
        ("report.strategy", "Strategy Report"),
    ],
    media_types: [
        ("image/png", "PNG"),
        ("application/json", "JSON"),
        ("application/zip", "ZIP"),
        ("text/plain", "Plain Text"),
    ],
    checksum: "Checksum",
    none: "—",
    count_verified_prefix: "{} (incomplete read: verified prefix only)",
    count_no_repair_log: "—(this storage format keeps no repair log)",
    count_not_stated: "—(not stated by the Runtime)",
    recovery_states: ["Recovered", "Unresolved", "Unknown"],
    recovery_gaps: [
        ("missing_relation", "Missing Relation"),
        ("conflicting_outcome", "Conflicting Outcome"),
        ("source_incomplete", "Source Incomplete"),
        ("context_limit", "Context Limit"),
    ],
    run_prefix: "Run: ",
    failed_recovered: "failed at #{}, recovered at #{}",
    failed_only: "failed at #{}, no recovery seen",
    gap_prefix: "; gap ",
    join: "; ",
    recovered_badge: "Recovered",
    integrity_ok: "Intact",
    integrity_bad: "Not intact: read_complete={} · corrupt tail={}",
    writer_absent: "No writer recorded",
    writer_locked: "Record held open ({} bytes)",
    writer_running: "{} · PID {} · still running · since {}",
    writer_stopped: "{} · PID {} · stopped · since {}",
    writer_runtime: "Running Runtime · PID {} · {} · since {}",
    source_online: "Online · runtime-client to the running Runtime",
    source_offline_requested: "Offline · by --source offline",
    source_offline_absent: "Offline · auto: no runtime-info.json in the state root",
    source_offline_failed: "Offline · auto: connecting to the Runtime failed with {} ({})",
    source_unopened: "ledger could not be opened: {} ({}) · {}",
    source_unopened_hint: "the state root has no ledger yet, most likely because the Runtime has never been started here; use Start in the launcher",
    io_kind_text: " · io kind {}",
    ledger_unopened: "Ledger Not Opened",
    list_unopened: "Ledger not opened: no events were read; the instance card says why",
    age_days: "{} days ago",
    age_hours: "{} hours ago",
    age_minutes: "{} minutes ago",
    age_seconds: "{} seconds ago",
    frame_size: "Frame {}×{}",
    frame_size_missing: "Frame Size Not Recorded",
    frame_reading: "Reading and verifying all {} bytes…",
    frame_verified: "Verified frame {}×{} · whole sha256 checked",
    frame_no_artifact: "No capture frame on this event; geometry only",
    frame_unavailable: "Material not given: {}",
    frame_evicted: "Material evicted ({}): intent #{}{} · observed through #{}",
    frame_decode_failed: "PNG decode failed: {}",
    frame_too_large: "Material of {} bytes is over the console's limit of {} bytes",
    filter_id_error: "The id must be a whole correlation_ / request_ / run_ / task_ / instance_ identifier",
    filter_instance_conflict: "Pick a port or type an instance id, not both",
    filter_rejected: "Filter rejected: {}",
    read_failed: "Read failed: {}",
    launcher_title: "Launcher",
    start: "Start",
    request_shutdown: "Request Shutdown",
    runtime_running: "Runtime Running · PID {} · Owner Epoch {}",
    runtime_not_running: "Runtime Not Running · {} ({})",
    already_running: "Already Running, Nothing Started",
    thread_failed: "Starting a Background Thread Failed: {}",
    start_unwatched: "actingd Launched (PID {}), but the Readiness Thread Failed to Start: {}; Press Start Again to Probe Whether It Is Ready",
    start_busy: "The Previous Start Is Still Waiting for Readiness",
    key_not_configured: "{} Not Configured in acui.toml",
    key_not_absolute: "{} in acui.toml Is Not an Absolute Path: {}",
    log_dir_failed: "Cannot Create Log Directory {}: {}",
    spawn_failed: "Starting {} Failed: {}",
    child_status_failed: "Reading the Child's Status Failed: {}",
    start_waiting: "Started PID {} · Waiting for Readiness {}/{} · Log {}",
    start_exited: "actingd Exited with Code {} · {} · Log {}",
    start_ready: "Runtime Ready · PID {} · Owner Epoch {}",
    restart_online: "This Console Reads Offline; Restart with --source online to Read It",
    start_not_ready: "Not Ready After {} Attempts · Last Error {} ({})",
    start_recorded: "Action Recorded at #{}",
    start_record_refused: "Action Record Refused: {} · Client {} ({})",
    start_record_failed: "Action Record Failed: {} ({})",
    log_no_fatal: "No FATAL actingd: Line in the Log",
    log_unreadable: "Reading the Log Failed: {}",
    unlock_owner: "Unlock Owner…",
    unlock_statement: "Confirm: the Device Resources of the Last Runtime Are Released",
    unlock_confirm: "Confirm and Unlock",
    unlock_busy: "The Unlock Is Still Running",
    unlock_running: "Running actingd unlock-owner --actor {} --confirm-resources-released…",
    unlock_ok: "Unlocked Owner Epoch {} · Disposition Before {} · owner.lock Revision {} · Start Retried Once (See the Line Above)",
    unlock_ok_nonzero: "unlock-owner Said ok but Exited with Code {}: Not Taken as Unlocked, Start Not Retried · Owner Epoch {} · Disposition Before {} · owner.lock Revision {}",
    unlock_failed: "Unlock Failed: {} (Stage {}) · journal_appended={} · Exit Code {}",
    unlock_fatal: "unlock-owner Exited with Code {} · {}",
    unlock_unparseable: "unlock-owner Output Unparseable: {} · Exit Code {}",
    unlock_field_invalid: "Field {} Missing or Off-Contract",
    unlock_no_output: "No JSON on stdout, No FATAL actingd: Line on stderr",
    unlock_timeout: "unlock-owner Not Finished Within {} s, Outcome Unknown",
    unlock_killed: "Killed and Reaped",
    unlock_kill_failed: "Killing It Failed: {}",
    unlock_unreaped: "Killed, but Reaping It Failed: {}",
    unlock_output_failed: "Reading unlock-owner Output Failed: {} · Exit Code {}",
    unlock_spawn_failed: "Running unlock-owner ({}) Failed: {}",
    shutdown_busy_retry: "Request Shutdown · Busy, Retry {}/{}",
    shutdown_attempts: "Attempt {}/{}",
    shutdown_accepted: "Shutdown Accepted · Receipt {} · Request {} · Action Recorded at #{}",
    shutdown_refused: "Shutdown Refused: {} · Client {} ({})",
    shutdown_failed: "Shutdown Request Failed: {} ({})",
    instance_config: "Instance Configuration",
    config_intro: "Lists the instances of actingd_config. Click a row to edit it in the form below, or Add Instance to start a new one, then Check and Save: a temporary file is written in the same directory and checked by actingd check-config, and only an ok replaces the file; keys and values the form does not manage are kept, key order is kept, and the whole file is rewritten as JSON indented by 2 spaces. Changes take effect when the Runtime restarts.",
    add_instance: "Add Instance",
    form_fields: ["alias (required)", "instance_id", "Binding", "adb_path", "nemu_app_index", "application_id", "capture_backend", "touch_backend"],
    binding_kinds: ["MuMu Index instance_index", "MuMu Name instance_name", "ADB Address host + port"],
    form_placeholders: ["instance_index (0–65535)", "instance_name", "host", "port (0–65535)", "Optional: empty uses the adb MuMu discovery reports", "Required: path to the adb executable", "Optional (0–4294967295)"],
    optional_note: "adb_path is required with an ADB address and optional with a MuMu binding; nemu_app_index is optional. The form does not check application_id or the two backends: whether they are needed and valid is decided by check-config. check-config also checks the nemu_app_index pairing; only what needs the MuMu discovery result (the MuMuManager version and capabilities, exactly one discovered match, declared values such as adb_path against the discovered ones, the ADB endpoint) waits until the Runtime starts. An empty box writes no key.",
    check_and_save: "Check and Save",
    id_failed: "Generating an instance_id Failed: {}",
    value_missing: "{} Must Not Be Empty",
    value_not_number: "{} Must Be a Whole Number 0–{}: {}",
    config_missing: "{} Does Not Exist",
    config_unreadable: "Reading {} Failed: {}",
    config_not_json: "{} Is Not Valid JSON: {}",
    config_no_instances: "{} Has No instances Array",
    checking: "Checking with check-config…",
    candidate_failed: "Writing the Temporary File {} Failed: {}",
    reader_failed: "Starting a Thread to Read check-config's Output Failed: {}",
    check_timeout: "check-config Did Not Finish Within {} s",
    check_unparsed: "check-config Output Not Recognized (Exit Code {}): {}",
    check_failed: "check-config Rejected It · error.code {} · stage {}",
    check_ok_nonzero: "check-config Said ok but Exited with {}; Not Saved",
    check_read_failed: "Reading check-config's Output Failed (Exit Code {}): {}",
    check_reader_lost:
        "The Thread Reading check-config's Output Ended Abnormally; No Output Obtained (Exit Code {})",
    check_stopped: "; check-config Was Terminated",
    check_unstoppable: "; Terminating check-config Failed ({}); It May Still Be Running",
    check_unreaped: "; check-config Was Terminated, but Reaping It Failed ({})",
    replace_failed: "Replacing {} Failed: {}",
    candidate_left: "; Temporary File {} Not Removed: {}",
    config_unchanged: " · The Config File Was Not Changed",
    saved: "Saved to {} (check-config ok) · Takes Effect When the Runtime Restarts",
    saved_running: "Now: {} · In the Main Window, Request Shutdown, Then Start Once It Has Stopped",
    saved_stopped: "Now: {} · Start in the Main Window Runs the New Configuration",
    config_listed: "{} · Instances: {}",
    config_bad_entry: "In {}, instances Entry {} Is Not an Object",
    ledger_online: "Ledger Binding: Not Given Online",
    ledger_failed: "Reading Ledger Bindings Failed: {}",
    ledger_port: "Bound in the Ledger · Port {}",
    ledger_outside_map:
        "Bound in the Ledger · Latest Binding Outside the Port Map (Serial-Configured or No Port)",
    ledger_none: "No Ledger Binding for This Instance",
    binding_index: "MuMu Index {}",
    binding_name: "MuMu Name {}",
    binding_adb: "ADB {}:{}",
    binding_serial: "ADB Serial {}",
    binding_none: "No Binding Key in the File",
    binding_fixture: "fixture_backend (No Device)",
    instance_detail: "{} · App {} · Capture {} · Touch {}",
    entry_gone: "{} Is No Longer in the Config File (Changed Elsewhere)",
    entry_no_id: "This Entry Has No String instance_id and Cannot Be Edited Here",
    entry_serial: "This Entry Sets serial, Which the Form Cannot Represent, and Cannot Be Edited Here",
    entry_fixture: "This Entry Has a fixture_backend, Which the Form Cannot Represent, and Cannot Be Edited Here",
    entry_no_binding: "This Entry Has No Binding Key in the File (No MuMu Index or Name, host / port or serial), Which the Form Cannot Represent, and Cannot Be Edited Here",
    row_no_id: "Not Editable: No String instance_id",
    instances_none: "No Registered Instance",
    offline_not_provided: "Not Provided Offline",
    facts_none: "No Task Fact",
    facts_no_events: "No Event in the Ledger Yet",
    facts_not_available: "Not Available: {}",
    instances_unread: "Not Read, See Below",
    lease_active: "Leased",
    lease_cooldown: "Takeover Cooldown",
    lease_idle: "Idle",
    lease_queued: "{} · {} Queued",
    not_registered: "Not Registered (Task Facts Only)",
    fact_unrecorded: "Not Recorded",
    host_failure: " · Host {} ({})",
    discover: "Discover Instances",
    discover_use: "Use Selected",
    discover_pick: "Pick a Discovered Instance…",
    discovering: "Asking the Runtime to Discover Instances…",
    discovered: "Instances Found: {} · MuMuManager {} · at Sequence {}",
    discover_refused: "Discovery Refused: {} · Client {} ({})",
    discover_failed: "Discovery Failed: {} ({})",
    discover_spawn_failed: "Starting the Discovery Thread Failed: {}",
    discovered_index: "Index {}",
    instance_running: "Running",
    instance_stopped: "Not Running",
    android_version: "Android {}",
    bound_to: "Bound to {}",
    discover_bound: "Index {} Is Already Bound to {} by the Running Runtime; No New Entry",
    discover_listed: "The File Already Has an Entry for Index {} ({}); Edit It in the List Above",
    discover_applied: "New Entry from Discovery: MuMu Index {} ({}). Fill In the Alias and the Rest, Then Check and Save",
};

impl Labels {
    /// The label for a field key; the key itself when the table has no entry.
    pub fn field<'a>(&self, key: &'a str) -> &'a str {
        pick(&self.fields, key).unwrap_or(key)
    }

    /// The name for a wire code, or the wire code itself.
    pub fn artifact_kind<'a>(&self, wire: &'a str) -> &'a str {
        pick(&self.artifact_kinds, wire).unwrap_or(wire)
    }

    pub fn media_type<'a>(&self, wire: &'a str) -> &'a str {
        pick(&self.media_types, wire).unwrap_or(wire)
    }

    pub fn source<'a>(&self, wire: &'a str) -> &'a str {
        pick(&self.sources, wire).unwrap_or(wire)
    }

    pub fn recovery_gap<'a>(&self, wire: &'a str) -> &'a str {
        pick(&self.recovery_gaps, wire).unwrap_or(wire)
    }

    pub fn provenance<'a>(&self, wire: &'a str) -> &'a str {
        pick(&self.provenances, wire).unwrap_or(wire)
    }
}

fn pick(table: &[(&'static str, &'static str)], key: &str) -> Option<&'static str> {
    table
        .iter()
        .find(|(wire, _)| *wire == key)
        .map(|(_, label)| *label)
}

/// Substitutes `{}` in a table string, left to right. The tables are the only
/// source of these templates, so a missing value just leaves the text short.
pub fn fill(template: &str, values: &[&str]) -> String {
    let mut text = String::with_capacity(template.len());
    let mut rest = template;
    for value in values {
        match rest.split_once("{}") {
            Some((head, tail)) => {
                text.push_str(head);
                text.push_str(value);
                rest = tail;
            }
            None => break,
        }
    }
    text.push_str(rest);
    text
}
